cluster:
    name: ${CLUSTER_NAME}

plugin.mandatory: cloud-aws

path:
  logs: /var/log
  data: /var/esdata

action.disable_delete_all_indices: true

cloud.aws:
  access_key: ${AWS_ACCESS_KEY}
  secret_key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}

bootstrap.mlockall: true

discovery:
  type: ec2
  ec2:
    ping_timeout: 120s
    tag.Name: ${EC2_TAG_NAME}

discovery.zen:
  minimum_master_nodes: ${MASTER_NODES}
  ping_timeout: 1m
  ping_retries: 5
  ping:
    multicast.enabled: false

script.engine.groovy.inline.update: on
script.engine.groovy.inline.aggs: on
script.engine.groovy.inline.search: on

network:
    host: _ec2_

http:
    host: 0.0.0.0
    compression: true

    cors:
        enabled: true
        allow-origin: '*'

node.data:   ${NODE_DATA}
node.master: ${NODE_MASTER}

threadpool.bulk.queue_size: ${BULK_QUEUE_SIZE}
